schema 
{
    query: Query,
    mutation: Mutation
}


type TEACHER 
{
    TEACHER: String!,
    TEACHER_NAME: String!,
    PULPIT: String!
}

type FACULTY 
{
    FACULTY: String!,
    FACULTY_NAME: String!
}

type SUBJECT 
{
    SUBJECT: String!,
    SUBJECT_NAME: String!,
    PULPIT: String!
}

type PULPIT 
{
    PULPIT: String!,
    PULPIT_NAME: String!,
    FACULTY: String!
}

type One 
{
    FACULTY: String!,
    TEACHERS:[TEACHER]
}

type Two 
{
    PULPIT: String!,
    PULPIT_NAME: String!,
    FACULTY: String!,
    SUBJECTS:[SUBJECT]
}

type Query 
{
    getTeachers(TEACHER: String): [TEACHER],
    getSubjects(SUBJECT: String): [SUBJECT],
    getFaculties(FACULTY: String): [FACULTY],
    getPulpits(PULPIT: String): [PULPIT],
    getTeachersByFaculty(FACULTY: String!): [One],
    getSubjectsByFaculty(FACULTY: String!): [Two]
}

type Mutation 
{
    delFaculty(FACULTY: String!): FACULTY,
    delPulpit(PULPIT: String!): PULPIT,
    delTeacher(TEACHER: String!): TEACHER,
    delSubject(SUBJECT: String!): SUBJECT
    setFaculty(FACULTY: String!, FACULTY_NAME: String!): FACULTY,
    setPulpit(PULPIT: String!, PULPIT_NAME: String!, FACULTY: String!): PULPIT,
    setTeacher(TEACHER: String!, TEACHER_NAME: String!, PULPIT: String!): TEACHER,
    setSubject(SUBJECT: String!, SUBJECT_NAME: String!, PULPIT: String!): SUBJECT,
}
